#!/bin/bash -eu

. "$plugin_dir/functions"

create_app_skel
install_tomcat7
install_jmx_invoker
install_jmxtrans_agent
install_server_config
install_web_container_extras
install_app
write_metadata
write_config
write_control
