#!/bin/bash

set -e
set -u

control_dir="$(dirname $0)"
. "$control_dir/config"

echo -e "\n##### BEGIN TOMCAT7 INFO #####"
_dir=$(pwd)
cd "$app_dir/.genapp/setup_status"
    for _file in *; do
        echo -e "\n----- Setup status for $_file is: -----" 
        cat "$_file"
    done
cd "$_dir"
echo -e "\n----- Context.xml file is: -----"
cat "$app_dir/server/conf/context.xml"
echo -e "\n----- Env file is: -----"
cat "$control_dir/env"
echo -e "\n----- Env_safe file is: -----"
cat "$control_dir/env_safe"
echo -e "\n----- Config file is: -----"
cat "$control_dir/config"
echo -e "\n----- Metadata file is: -----"
cat "$app_dir/.genapp/metadata.json"
echo -e "\n##### END TOMCAT7 INFO #####"

